test
CREATE SEQUENCE BOOK_BEAUTY_SEQ NOCACHE ;
CREATE TABLE BOOK_BEAUTY (
  BOOK_BEAUTY_ID NUMBER primary key,
  USER_ID NUMBER NOT NULL,
  PET_ID NUMBER NOT NULL,
  BEAUTY_ID NUMBER NOT NULL
);

CREATE SEQUENCE BASKET_SEQ NOCACHE ;
CREATE TABLE BASKET (
  BASKET_ID NUMBER primary key ,
  PRODUCT_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  QUANTITY NUMBER NOT NULL
);

CREATE SEQUENCE BEAUTY_SEQ NOCACHE ;
CREATE TABLE BEAUTY (
  BEAUTY_ID NUMBER primary key ,
  NAME VARCHAR2(200),
  PHONE VARCHAR2(255),
  ADDR1 VARCHAR2(1000),
  ADDR2 VARCHAR2(1000),
  ZIPCODE VARCHAR2(255),
  STATUS_ID NUMBER
);

CREATE SEQUENCE BEAUTY_STATUS_SEQ NOCACHE ;
CREATE TABLE BEAUTY_STATUS (
  BEAUTY_STATUS_ID NUMBER PRIMARY KEY ,
  STATUS VARCHAR2(100)
);

CREATE SEQUENCE BUY_CONFIRMED_SEQ NOCACHE ;
CREATE TABLE BUY_CONFIRMED (
  BUY_CONFIRMED_ID NUMBER PRIMARY KEY ,
  CONFIRMATION VARCHAR2(10) NOT NULL
);

CREATE SEQUENCE CANCEL_SEQ NOCACHE ;
CREATE TABLE CANCEL (
  CANCEL_ID NUMBER NOT NULL,
  ORDER_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  APPLY_DATE DATE NOT NULL,
  REASON VARCHAR2(255) NOT NULL,
  PROGRESS_ID NUMBER,
  QUANTITY VARCHAR2(255) NOT NULL,
  PRICE NUMBER NOT NULL,
  CANC_DATE DATE,
  CANC_RESULT_ID NUMBER,
  COMP_DATE DATE
);

CREATE SEQUENCE CANCELS_RES_SEQ NOCACHE ;
CREATE TABLE CANCELS_RES (
  CANCEL_RES_ID NUMBER PRIMARY KEY,
  CANCEL_RES VARCHAR2(255)
);

CREATE SEQUENCE CATEGORY_SEQ NOCACHE ;
CREATE TABLE CATEGORY (
  CATE_ID NUMBER PRIMARY KEY ,
  CATEGORY VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE CHANGE_RES_SEQ NOCACHE ;
CREATE TABLE CHANGE_RES (
  CHANGE_RES_ID NUMBER PRIMARY KEY ,
  CHANG_RES VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE CHANGES_SEQ NOCACHE ;
CREATE TABLE CHANGES (
  CHANGE_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  ORDER_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  QUANTITY NUMBER,
  REASON VARCHAR2(255) NOT NULL,
  APPLY_DATE DATE NOT NULL,
  SELLER_COMMENT VARCHAR2(255),
  PROGRESS_ID NUMBER,
  RESULT_ID NUMBER,
  COMP_DATE DATE
);

CREATE SEQUENCE CLOSED_DATE_SEQ NOCACHE ;
CREATE TABLE CLOSED_DATE (
  CLOSE_DATE_ID NUMBER PRIMARY KEY ,
  CLOSED_DATE DATE,
  VET_ID NUMBER
);

CREATE SEQUENCE DELIV_STATUS_SEQ NOCACHE ;
CREATE TABLE DELIV_STATUS (
  DELI_STATUS_ID NUMBER PRIMARY KEY ,
  DELI_STATUS VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE DIAGNOSIS_SEQ NOCACHE ;
CREATE TABLE DIAGNOSIS (
  DIAGNO_ID NUMBER PRIMARY KEY ,
  VET_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  PET_ID NUMBER NOT NULL,
  DIGONO VARCHAR2(255) NOT NULL,
  IMAGE_URL_ID NUMBER NOT NULL,
  CREATE_DATE DATE NOT NULL
);

CREATE SEQUENCE DP_STATUS_SEQ NOCACHE ;
CREATE TABLE DP_STATUS (
  DP_STATUS_ID NUMBER PRIMARY KEY ,
  DP_STATUS VARCHAR2(255) NOT NULL
);


CREATE SEQUENCE BOOK_ID_SEQ NOCACHE;
CREATE TABLE BOOKING_VET (
  BOOK_ID NUMBER PRIMARY KEY ,
  USER_ID NUMBER NOT NULL,
  PET_ID NUMBER NOT NULL,
  BOOK_DATE DATE NOT NULL,
  BOOK_TIME DATE NOT NULL ,
  VET_ID NUMBER NOT NULL ,
  COMMENTS VARCHAR2(255)
);

CREATE SEQUENCE IMAGES_URL_SEQ NOCACHE ;
CREATE TABLE IMAGES_URL (
  IMAGE_URL_ID NUMBER PRIMARY KEY ,
  IMAGE_URL VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE INVOICE_SEQ NOCACHE ;
CREATE TABLE INVOICE (
  INVOICE_ID NUMBER NOT NULL UNIQUE ,
  VET_ID NUMBER NOT NULL,
  PET_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  DIAGNOSIS NUMBER NOT NULL,
  SERVICE VARCHAR2(255) NOT NULL,
  PRICE NUMBER NOT NULL,
  INVOICE_DATE DATE NOT NULL,
  COMMENTS VARCHAR2(2000)
);

CREATE SEQUENCE INVOICE_ITEM_SEQ NOCACHE ;
CREATE TABLE INVOICE_ITEMS (
  ITEM_ID NUMBER NOT NULL,
  INVOICE_ID NUMBER NOT NULL,
  CLIENT_ID NUMBER NOT NULL,
  CREATE_DATE DATE NOT NULL,
  ITEMS VARCHAR2(255) NOT NULL,
  QUANTITY NUMBER NOT NULL,
  UNIT_PRICE NUMBER NOT NULL,
  AMOUNT VARCHAR2(255) NOT NULL,
  TAX VARCHAR2(10) NOT NULL
);

CREATE SEQUENCE LODGE_VET_SEQ NOCACHE ;
CREATE TABLE LODGE_VET (
  LODGE_ID NUMBER PRIMARY KEY ,
  USER_ID NUMBER,
  PET_ID NUMBER,
  VET_ID NUMBER
);

-- CREATE TABLE "NOTIFICATION-RECEVE" (
--   "ID" NUMBER NOT NULL,
--   "USERID" NUMBER,
--   "PETID" NUMBER,
--   "NOTIFICATION" VARCHAR2(255) NOT NULL,
--   "DATE" DATE NOT NULL,
--   "RESERV-ID" NUMBER,
--   "VET-ID" NUMBER,
--   "CHECK" VARCHAR2(255) NOT NULL,
--   "TYPE" NUMBER NOT NULL,
--   CONSTRAINT "_COPY_11" PRIMARY KEY ("ID")
-- );

-- CREATE TABLE "NOTIFICATION-SEND" (
--   "ID" NUMBER NOT NULL,
--   "USERID" NUMBER,
--   "PETID" NUMBER,
--   "NOTIFICATION" VARCHAR2(255) NOT NULL,
--   "DATE" DATE NOT NULL,
--   "RESERV-ID" NUMBER,
--   "VET-ID" NUMBER,
--   "CHECK" VARCHAR2(255) NOT NULL,
--   "TYPE" NUMBER NOT NULL,
--   CONSTRAINT "_COPY_11_COPY_1" PRIMARY KEY ("ID")
-- );

CREATE SEQUENCE OPTIONS_SEQ NOCACHE ;
CREATE TABLE OPTIONS (
  OPTIONS_ID NUMBER PRIMARY KEY ,
  OPTIONS VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE ORDER_TYPE_SEQ NOCACHE ;
CREATE TABLE ORDER_TYPE (
  ORDER_TYPE_ID NUMBER PRIMARY KEY ,
  TYPE VARCHAR2(255) NOT NULL
);



